### ISSUE TITLE
Show package downloads

### ISSUE THREAD

**Issue by gkaimakas** [bower/stats-bower#22]
Is it possible to show a counter with the package downloads the same way npm does?

**Comment by jeremyckahn** [comment]
I would also love to see this feature!

**Comment by jacobscarter** [comment]
+1

**Comment by jdalton** [comment]
:1:

**Comment by samccone** [comment]
> Is it possible to show a counter with the package downloads the same way npm does

Hypothetically @gkaimakas @jeremyckahn @jacobscarter @jdalton  would you like to see this on this screen?

![screen shot 2015-07-20 at 7 09 20 pm](https://cloud.githubusercontent.com/assets/883126/8789665/df58005e-2f12-11e5-854f-ed0afb047d7f.png)


http://bower.io/search/?q=underscore

**Comment by jdalton** [comment]
Sure!

**Comment by jeremyckahn** [comment]
Yes, that would be great!

**Comment by gkaimakas** [comment]
Well, that only shows how many people have stared the repository, not how many have downloaded it. The way npm does it is that it displays the downloads for the last day, last week and last month with each counter being updated each day

**Comment by gkaimakas** [comment]
![angular validators](https://cloud.githubusercontent.com/assets/1790873/8797354/8da85c40-2fa3-11e5-8bae-a6f630c80651.jpg)

**Comment by jeremyckahn** [comment]
@gkaimakas, I believe that @samccone was asking if that's where in the UI we would like to see the download statistics.

Given that the Bower UI doesn't have dedicated project pages, that seems like the simplest place to display that number, IMO.

**Comment by gkaimakas** [comment]
oh, yes, you are right :)

**Comment by samccone** [comment]
> @gkaimakas, I believe that @samccone was asking if that's where in the UI we would like to see the download statistics.

Correct :white_check_mark:
